export const CONSTANTS = {
    SPLASH_SCREEN_HIDE_REQUEST: 'SPLASH_SCREEN_HIDE_REQUEST',
    SPLASH_SCREEN_HIDE_SUCCESS: 'SPLASH_SCREEN_HIDE_SUCCESS',
    SPLASH_SCREEN_HIDE_FAILURE: 'SPLASH_SCREEN_HIDE_FAILURE',

    CLICK_NEXT_REQUEST: 'CLICK_NEXT_REQUEST',
    CLICK_NEXT_SUCCESS: 'CLICK_NEXT_SUCCESS',
    CLICK_NEXT_FAILURE: 'CLICK_NEXT_FAILURE',

    SCALE_METER_VALUE_CHANGE_REQUEST: 'SCALE_METER_VALUE_CHANGE_REQUEST',
    SCALE_METER_VALUE_CHANGE_SUCCESS: 'SCALE_METER_VALUE_CHANGE_SUCCESS',
    SCALE_METER_VALUE_CHANGE_FAILURE: 'SCALE_METER_VALUE_CHANGE_FAILURE',

    PYRAMID_VALUE_CHANGE_REQUEST: 'PYRAMID_VALUE_CHANGE_REQUEST',
    PYRAMID_VALUE_CHANGE_SUCCESS: 'PYRAMID_VALUE_CHANGE_SUCCESS',
    PYRAMID_VALUE_CHANGE_FAILURE: 'PYRAMID_VALUE_CHANGE_FAILURE',
}