export const COLORS = {
    maincolor: '#325d6e',
    base: "#6edbe6",
    darkBase: '#456d7c',
    lightbase: '#c8f7fc',
    white: '#FFFFFF',
    lightblue: '#85BBCE',
    lightgrey: '#CCCCCC',
    black: '#000000',
    red: 'red',
    pink: 'pink',
    grey: 'grey',
    transparent: '#FFFFFF00',
    green: 'green',
}
